import {describe, expect, test} from '@jest/globals';
import {getTatarNumber} from '../src/utils';

describe('numbers', () => {
  test('numbers', () => {
    expect(getTatarNumber(1)).toBe('бер');
    expect(getTatarNumber(2)).toBe('ике');
    expect(getTatarNumber(3)).toBe('өч');
    expect(getTatarNumber(4)).toBe('дүрт');
    expect(getTatarNumber(5)).toBe('биш');
    expect(getTatarNumber(6)).toBe('алты');
    expect(getTatarNumber(7)).toBe('җиде');
    expect(getTatarNumber(8)).toBe('сигез');
    expect(getTatarNumber(9)).toBe('тугыз');
    expect(getTatarNumber(10)).toBe('ун');
    expect(getTatarNumber(11)).toBe('ун бер');
    expect(getTatarNumber(12)).toBe('ун ике');
    expect(getTatarNumber(13)).toBe('ун өч');
    expect(getTatarNumber(14)).toBe('ун дүрт');
    expect(getTatarNumber(15)).toBe('ун биш');
    expect(getTatarNumber(16)).toBe('ун алты');
    expect(getTatarNumber(17)).toBe('ун җиде');
    expect(getTatarNumber(18)).toBe('ун сигез');
    expect(getTatarNumber(19)).toBe('ун тугыз');
    expect(getTatarNumber(20)).toBe('егерме');
    expect(getTatarNumber(21)).toBe('егерме бер');
    expect(getTatarNumber(32)).toBe('утыз ике');
    expect(getTatarNumber(43)).toBe('кырык өч');
    expect(getTatarNumber(54)).toBe('илле дүрт');
    expect(getTatarNumber(65)).toBe('алтмыш биш');
    expect(getTatarNumber(76)).toBe('житмеш алты');
    expect(getTatarNumber(87)).toBe('сиксән җиде');
    expect(getTatarNumber(98)).toBe('туксан сигез');
    expect(getTatarNumber(100)).toBe('йөз');
    expect(getTatarNumber(101)).toBe('йөз бер');
    expect(getTatarNumber(130)).toBe('йөз утыз');
    expect(getTatarNumber(142)).toBe('йөз кырык ике');
    expect(getTatarNumber(1420)).toBe('бер мең дүрт йөз егерме');
    expect(getTatarNumber(1425)).toBe('бер мең дүрт йөз егерме биш');
    expect(getTatarNumber(14250)).toBe('ун дүрт мең ике йөз илле');
    expect(getTatarNumber(14251)).toBe('ун дүрт мең ике йөз илле бер');
    expect(getTatarNumber(142510)).toBe('йөз кырык ике мең биш йөз ун');
    expect(getTatarNumber(142514)).toBe('йөз кырык ике мең биш йөз ун дүрт');
    expect(getTatarNumber(100000)).toBe('йөз мең');
    expect(getTatarNumber(100001)).toBe('йөз мең бер');
    expect(getTatarNumber(100010)).toBe('йөз мең ун');
    expect(getTatarNumber(100600)).toBe('йөз мең алты йөз');
    expect(getTatarNumber(105000)).toBe('йөз биш мең');
    expect(getTatarNumber(104001)).toBe('йөз дүрт мең бер');
    expect(getTatarNumber(110020)).toBe('йөз ун мең егерме');
  });
});
